# Generated by Django 5.0.3 on 2024-03-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
