# Generated by Django 5.0.3 on 2024-03-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp1', '0002_rename_aoellido_usuario_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
